INSERT INTO DCOMS.MENU ("NAME", PRICE) 
	VALUES ('Burger', '50');
INSERT INTO DCOMS.MENU ("NAME", PRICE) 
	VALUES ('Sandwich', '40');
INSERT INTO DCOMS.MENU ("NAME", PRICE) 
	VALUES ('Breakfast Set', '30');
INSERT INTO DCOMS.MENU ("NAME", PRICE) 
	VALUES ('Drink', '10');
INSERT INTO DCOMS.MENU ("NAME", PRICE) 
	VALUES ('Fries', '10');
INSERT INTO DCOMS.MENU ("NAME", PRICE) 
	VALUES ('Dinner Set', '70');
INSERT INTO DCOMS.MENU ("NAME", PRICE) 
	VALUES ('Coffee (Hot)', '15');
