INSERT INTO DCOMS.CUS_LOGIN (FNAME, LNAME, IC, USERNAME, PASSWORD) 
	VALUES ('Jimmy', 'Kimmel', 'JK123456', 'jimmy', 'jimmy123');
INSERT INTO DCOMS.CUS_LOGIN (FNAME, LNAME, IC, USERNAME, PASSWORD) 
	VALUES ('Mark', 'Wahl', 'MW123456', 'mark', '12345');
INSERT INTO DCOMS.CUS_LOGIN (FNAME, LNAME, IC, USERNAME, PASSWORD) 
	VALUES ('Apple', 'Tim', 'AP1234565', 'tim', 'tim123');
INSERT INTO DCOMS.CUS_LOGIN (FNAME, LNAME, IC, USERNAME, PASSWORD) 
	VALUES ('Henry', 'Ford', 'HF123546', 'henry', 'henryford');
INSERT INTO DCOMS.CUS_LOGIN (FNAME, LNAME, IC, USERNAME, PASSWORD) 
	VALUES ('Fred', 'Lynn', 'FL123546', 'fred', 'fred123');
