INSERT INTO DCOMS.AD_LOGIN (USERNAME, PASSWORD) 
	VALUES ('oliver', 'oliver123');
INSERT INTO DCOMS.AD_LOGIN (USERNAME, PASSWORD) 
	VALUES ('Don', 'Don123');
INSERT INTO DCOMS.AD_LOGIN (USERNAME, PASSWORD) 
	VALUES ('Mark', 'mark123');
INSERT INTO DCOMS.AD_LOGIN (USERNAME, PASSWORD) 
	VALUES ('admin', 'admintry');
INSERT INTO DCOMS.AD_LOGIN (USERNAME, PASSWORD) 
	VALUES ('Chris', 'chriss');
INSERT INTO DCOMS.AD_LOGIN (USERNAME, PASSWORD) 
	VALUES ('Erikson', 'erikson123');
